# Generated by Django 5.2.9 on 2025-12-28 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('matter_type', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('contract', 'Contract'), ('corporate', 'Corporate'), ('immigration', 'Immigration'), ('real_estate', 'Real Estate'), ('ip', 'Intellectual Property'), ('employment', 'Employment'), ('bankruptcy', 'Bankruptcy'), ('tax', 'Tax'), ('personal_injury', 'Personal Injury'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('client_role', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('petitioner', 'Petitioner'), ('respondent', 'Respondent'), ('appellant', 'Appellant'), ('appellee', 'Appellee'), ('other', 'Other')], default='other', max_length=20)),
                ('jurisdiction_details', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('conflict_check', 'Conflict Check'), ('matching', 'Attorney Matching'), ('open', 'Open'), ('in_progress', 'In Progress'), ('hold', 'On Hold'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('status_notes', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('statute_of_limitations', models.DateField(blank=True, null=True)),
                ('next_action_date', models.DateField(blank=True, null=True)),
                ('next_action_description', models.CharField(blank=True, max_length=255)),
                ('conflict_check_completed', models.BooleanField(default=False)),
                ('conflict_check_passed', models.BooleanField(default=False)),
                ('conflict_check_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('agreed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_structure', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'matter',
                'verbose_name_plural': 'matters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private notes are only visible to the author')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'matter note',
                'verbose_name_plural': 'matter notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('government', 'Government Entity')], default='individual', max_length=20)),
                ('role', models.CharField(choices=[('opposing', 'Opposing Party'), ('witness', 'Witness'), ('related', 'Related Party'), ('other', 'Other')], default='opposing', max_length=20)),
                ('name_hash', models.CharField(db_index=True, max_length=64)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'matter party',
                'verbose_name_plural': 'matter parties',
            },
        ),
        migrations.CreateModel(
            name='MatterStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'matter status history',
                'verbose_name_plural': 'matter status histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
