# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorneys', '0002_initial'),
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='matter',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matter',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='attorneys.jurisdiction'),
        ),
        migrations.AddField(
            model_name='matter',
            name='practice_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matters', to='attorneys.practicearea'),
        ),
        migrations.AddField(
            model_name='matternote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matternote',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='matterparty',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='matterstatushistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matterstatushistory',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='matters.matter'),
        ),
    ]
