# Generated by Django 5.2.9 on 2026-01-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matters', '0003_alter_matter_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='jurisdiction_state',
            field=models.CharField(blank=True, help_text="US state code or name (e.g., 'CA', 'New York') when jurisdiction_type is State", max_length=100),
        ),
        migrations.AddField(
            model_name='matter',
            name='jurisdiction_type',
            field=models.CharField(choices=[('state', 'State'), ('federal', 'Federal'), ('international', 'International')], default='state', help_text='Type of jurisdiction: State, Federal, or International', max_length=15),
        ),
        migrations.AlterField(
            model_name='matter',
            name='matter_type',
            field=models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('family', 'Family'), ('contract', 'Contract'), ('corporate', 'Corporate'), ('immigration', 'Immigration'), ('real_estate', 'Real Estate'), ('probate', 'Probate'), ('ip', 'Intellectual Property'), ('employment', 'Employment'), ('bankruptcy', 'Bankruptcy'), ('tax', 'Tax'), ('personal_injury', 'Personal Injury'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
