# Generated by Django 5.2.9 on 2025-12-28 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'device token',
                'verbose_name_plural': 'device tokens',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('matter_created', 'Matter Created'), ('matter_updated', 'Matter Updated'), ('matter_assigned', 'Matter Assigned'), ('matter_completed', 'Matter Completed'), ('attorney_request', 'New Client Request'), ('attorney_accepted', 'Attorney Accepted'), ('attorney_declined', 'Attorney Declined'), ('new_message', 'New Message'), ('document_uploaded', 'Document Uploaded'), ('signature_requested', 'Signature Requested'), ('document_signed', 'Document Signed'), ('appointment_requested', 'Appointment Requested'), ('appointment_confirmed', 'Appointment Confirmed'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_reminder', 'Appointment Reminder'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('invoice_sent', 'Invoice Sent'), ('system_alert', 'System Alert'), ('account_update', 'Account Update')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_matter_updates', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_appointments', models.BooleanField(default=True)),
                ('email_payments', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_appointments', models.BooleanField(default=True)),
                ('sms_urgent_only', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_appointments', models.BooleanField(default=True)),
                ('push_documents', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
    ]
