# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorneys', '0001_initial'),
        ('matters', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'practice area',
                'verbose_name_plural': 'practice areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttorneyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attorney_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bar_number', models.CharField(max_length=50)),
                ('bar_state', models.CharField(max_length=100)),
                ('bar_admission_date', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('education', models.TextField(blank=True, help_text='Education history, one per line')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('fee_structure', models.CharField(choices=[('hourly', 'Hourly Rate'), ('flat', 'Flat Fee'), ('contingency', 'Contingency'), ('retainer', 'Retainer'), ('subscription', 'Subscription')], default='hourly', max_length=20)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_consultation', models.BooleanField(default=False)),
                ('malpractice_insurance', models.BooleanField(default=False)),
                ('insurance_carrier', models.CharField(blank=True, max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('bar_license_document', models.FileField(blank=True, null=True, upload_to='attorney_documents/bar_licenses/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='attorney_documents/insurance/')),
                ('is_accepting_clients', models.BooleanField(default=True)),
                ('max_active_cases', models.PositiveIntegerField(default=50)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_cases_completed', models.PositiveIntegerField(default=0)),
                ('office_address', models.TextField(blank=True)),
                ('office_city', models.CharField(blank=True, max_length=100)),
                ('office_state', models.CharField(blank=True, max_length=100)),
                ('office_postal_code', models.CharField(blank=True, max_length=20)),
                ('office_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attorneys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'attorney profile',
                'verbose_name_plural': 'attorney profiles',
            },
        ),
        migrations.AddField(
            model_name='attorneyavailability',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='attorneys.attorneyprofile'),
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jurisdiction',
                'verbose_name_plural': 'jurisdictions',
                'ordering': ['country', 'name'],
                'unique_together': {('state_code', 'country')},
            },
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='jurisdictions',
            field=models.ManyToManyField(related_name='attorneys', to='attorneys.jurisdiction'),
        ),
        migrations.AddField(
            model_name='attorneyprofile',
            name='practice_areas',
            field=models.ManyToManyField(related_name='attorneys', to='attorneys.practicearea'),
        ),
        migrations.CreateModel(
            name='AttorneyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='attorneys.attorneyprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_reviews', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='matters.matter')),
            ],
            options={
                'verbose_name': 'attorney review',
                'verbose_name_plural': 'attorney reviews',
                'ordering': ['-created_at'],
                'unique_together': {('attorney', 'client', 'matter')},
            },
        ),
    ]
