# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('matters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='documents.document'),
        ),
    ]
