# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentsignature',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentsignature',
            unique_together={('document', 'signer')},
        ),
    ]
