# Generated by Django 5.2.9 on 2025-12-28 21:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttorneyClientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_hash', models.CharField(db_index=True, max_length=64)),
                ('relationship_type', models.CharField(choices=[('current', 'Current Client'), ('past', 'Past Client'), ('adverse', 'Adverse Party'), ('related', 'Related Party')], default='current', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'attorney client record',
                'verbose_name_plural': 'attorney client records',
            },
        ),
        migrations.CreateModel(
            name='ConflictCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('clear', 'No Conflicts'), ('conflict', 'Conflict Found'), ('potential', 'Potential Conflict')], max_length=20)),
                ('names_checked_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conflict check',
                'verbose_name_plural': 'conflict checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflicting_name_hash', models.CharField(max_length=64)),
                ('conflict_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'conflict detail',
                'verbose_name_plural': 'conflict details',
            },
        ),
    ]
