# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorneys', '0002_initial'),
        ('conflicts', '0001_initial'),
        ('matters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneyclientrecord',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_records', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='attorneyclientrecord',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_records', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='conflictcheck',
            name='attorneys_checked',
            field=models.ManyToManyField(blank=True, related_name='conflict_checks_performed', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='conflictcheck',
            name='excluded_attorneys',
            field=models.ManyToManyField(blank=True, related_name='conflict_exclusions', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='conflictcheck',
            name='matter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_checks', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='conflictcheck',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_check_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflictdetail',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_details', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='conflictdetail',
            name='client_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conflicts.attorneyclientrecord'),
        ),
        migrations.AddField(
            model_name='conflictdetail',
            name='conflict_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='conflicts.conflictcheck'),
        ),
        migrations.AddIndex(
            model_name='attorneyclientrecord',
            index=models.Index(fields=['attorney', 'name_hash'], name='conflicts_a_attorne_cb119a_idx'),
        ),
    ]
