# Generated by Django 5.2.9 on 2025-12-28 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attorneys', '0002_initial'),
        ('matters', '0002_initial'),
        ('payments', '0002_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='matter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='matters.matter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='blockedtime',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='attorneys.attorneyprofile'),
        ),
        migrations.AddField(
            model_name='calendarintegration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='calendarintegration',
            unique_together={('user', 'provider')},
        ),
    ]
